import { PropertyProps } from "@/interfaces/index";
export const PROPERTYLISTINGSAMPLE: PropertyProps[] = [
  {
    id: 1,
    name: "Villa Ocean Breeze",
    address: { state: "Seminyak", city: "Bali", country: "Indonesia" },
    rating: 4.89,
    category: ["Luxury Villa", "Pool", "Free Parking"],
    price: 3200,
    offers: { bed: "3", shower: "3", occupants: "4-6" },
    image: "/assets/ListingImages/10001.png",
    discount: "",
    description: "A luxurious villa with ocean views, private pool, and all amenities.",
    reviews: []
  },
  {
    id: 2,
    name: "Mountain Escape Chalet",
    address: { state: "Aspen", city: "Colorado", country: "USA" },
    rating: 4.70,
    category: ["Mountain View", "Fireplace", "Self Checkin"],
    price: 1800,
    offers: { bed: "4", shower: "2", occupants: "5-7" },
    image: "/assets/ListingImages/10002.png",
    discount: "30",
    description: "Cozy chalet with breathtaking mountain views and modern amenities.",
    reviews: []
  },
  {
    id: 3,
    name: "Cozy Desert Retreat",
    address: { state: "Palm Springs", city: "California", country: "USA" },
    rating: 4.92,
    category: ["Desert View", "Pet Friendly", "Self Checkin"],
    price: 1500,
    offers: { bed: "2", shower: "1", occupants: "2-3" },
    image: "/assets/ListingImages/10003.png",
    discount: "",
    description: "Peaceful desert retreat perfect for relaxation and adventure.",
    reviews: []
  },
  {
    id: 4,
    name: "City Lights Penthouse",
    address: { state: "New York", city: "New York", country: "USA" },
    rating: 4.85,
    category: ["City View", "Free WiFi", "24h Checkin"],
    price: 4500,
    offers: { bed: "2", shower: "2", occupants: "2-4" },
    image: "/assets/ListingImages/10004.png",
    discount: "15",
    description: "Modern penthouse in the heart of the city with stunning skyline views.",
    reviews: []
  },
  {
    id: 5,
    name: "Riverside Cabin",
    address: { state: "Queenstown", city: "Otago", country: "New Zealand" },
    rating: 4.77,
    category: ["Riverside", "Private Dock", "Free Kayaks"],
    price: 2800,
    offers: { bed: "3", shower: "2", occupants: "4-6" },
    image: "/assets/ListingImages/10005.png",
    discount: "20",
    description: "Charming riverside cabin ideal for nature lovers and water activities.",
    reviews: []
  },
  {
    id: 6,
    name: "Modern Beachfront Villa",
    address: { state: "Sidemen", city: "Bali", country: "Indonesia" },
    rating: 4.95,
    category: ["Beachfront", "Private Pool", "Chef Service"],
    price: 5000,
    offers: { bed: "5", shower: "4", occupants: "8-10" },
    image: "/assets/ListingImages/10006.png",
    discount: "",
    description: "Luxury villa right on the beach with private pool and personal chef.",
    reviews: []
  },
  {
    id: 7,
    name: "Lakeside Chalet",
    address: { state: "Banff", city: "Alberta", country: "Canada" },
    rating: 4.65,
    category: ["Lakeside", "Mountain View", "Hiking Trails"],
    price: 2300,
    offers: { bed: "3", shower: "3", occupants: "4-5" },
    image: "/assets/ListingImages/10007.png",
    discount: "10",
    description: "Relaxing lakeside chalet surrounded by mountains and hiking trails.",
    reviews: []
  },
  {
    id: 8,
    name: "Tropical Garden Villa",
    address: { state: "Koh Samui", city: "Surat Thani", country: "Thailand" },
    rating: 4.80,
    category: ["Garden", "Free Parking", "Self Checkin"],
    price: 2750,
    offers: { bed: "3", shower: "3", occupants: "5-6" },
    image: "/assets/ListingImages/10008.png",
    discount: "25",
    description: "Tropical villa with lush gardens, privacy, and modern amenities.",
    reviews: []
  },
  {
    id: 9,
    name: "Urban Loft",
    address: { state: "Berlin", city: "Berlin", country: "Germany" },
    rating: 4.60,
    category: ["City Center", "Free WiFi", "24h Checkin"],
    price: 2000,
    offers: { bed: "2", shower: "1", occupants: "2-3" },
    image: "/assets/ListingImages/10009.png",
    discount: "",
    description: "Stylish urban loft in the heart of Berlin with modern conveniences.",
    reviews: []
  },
  {
    id: 10,
    name: "Secluded Forest Cabin",
    address: { state: "Whistler", city: "British Columbia", country: "Canada" },
    rating: 4.72,
    category: ["Secluded", "Hot Tub", "Self Checkin"],
    price: 2600,
    offers: { bed: "4", shower: "2", occupants: "5-7" },
    image: "/assets/ListingImages/10010.png",
    discount: "40",
    description: "Private forest cabin with hot tub and self check-in for ultimate privacy.",
    reviews: []
  },
  // Continue the rest with id: 11–20 similarly
];
